### ISSUE TITLE
Tests depend on deterministic ordering of attributes

### ISSUE THREAD

**Issue by rowanseymour** [Psycojoker/django-hamlpy#2]
https://github.com/nyaruka/django-hamlpy/blob/9224b44942b1c9261a76d02d4f9da45d2dd77a0a/hamlpy/elements.py#L137-L137 evaluates a parsed attribute dictionary as a Python dict, but that means attribute ordering is non-deterministic.

This leads to tests sometimes failing which depend on order, e.g. https://github.com/nyaruka/django-hamlpy/blob/37d63ad07bcc52a145640fc2bb2e10c62bb0420a/hamlpy/test/test_elements.py#L52

Question is whether html attribute order should match haml attribute order?

**Comment by Psycojoker** [comment]
I think that we should try to finish this other branch https://github.com/Psycojoker/django-hamlpy/tree/element_parser that, apparently, uses a real parser. This will solve this issue and avoid potential other ones generated by using regex to transform the attributes into a python dict.

**Comment by rowanseymour** [comment]
Yeah the regex approach is certainly fragile... do you know how close to finished that branch is?

**Comment by Psycojoker** [comment]
Sadly no, I've only saw it since someone proposed it to be merged https://github.com/jessemiller/HamlPy/pull/147 so I guess it's at least close to being ready.

**Comment by rowanseymour** [comment]
Looks like it has diverged quite a bit from master and doesn't run on Python 2.7.

How would you feel about this as temporary workaround https://github.com/nyaruka/django-hamlpy/commit/9e536890d50054c0d67c2c0c81f890d9dcc66f38 ?

**Comment by Psycojoker** [comment]
This fix seems totally acceptable in this situation for me.
