### ISSUE TITLE
Django template loader not working in 1.10?

### ISSUE THREAD

**Issue by Kangaroux** [Psycojoker/django-hamlpy#28]
I'm unable to get the template loader to work in Python 3.4.3, Django 1.10. The templates end in .haml and are rendered but the haml is not converted to HTML.

Settings file for templates looks like:

    TEMPLATES = [
      {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["web/templates"],
        'APP_DIRS': False,
        'OPTIONS': {
          'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.messages.context_processors.messages',
          ],
          'loaders': [
            'hamlpy.template.loaders.HamlPyFilesystemLoader',
            'hamlpy.template.loaders.HamlPyAppDirectoriesLoader',
          ]
        },
      },
    ]

**Comment by rowanseymour** [comment]
That's odd. Our unit tests definitely test the loaders on Django 1.10 / Python 3.4. Can you try debugging `HamlPyFilesystemLoader` to check that it's being used?

**Comment by Kangaroux** [comment]
Ok, I have no idea why it wasn't working before but it's fine now. Closing this..
