### ISSUE TITLE
Implement a proper attribute dictionary parser

### ISSUE THREAD

**Issue by rowanseymour** [Psycojoker/django-hamlpy#5]
We currently use regexes to transform the attribute dictionary into a python dict, and parse it with eval, which is fragile, and loses attribute ordering. We can either try merging https://github.com/jessemiller/HamlPy/tree/element_parser or just salvage what we need from that branch.

**Comment by rowanseymour** [comment]
Once #1 is merged I can make a PR for this. I grabbed https://github.com/a1s/HamlPy/tree/element_parser and merged it into a copy of my python3 branch, added support for boolean attributes which was already in master, and fixed Python 3 issues on the new code.

**Comment by Psycojoker** [comment]
Wow, that's a great news!

I wasn't feeling as ease with this `eval` trick at all. #1 has been merged so the path is free :)

**Comment by rowanseymour** [comment]
Fixed in #8 and #13
