### ISSUE TITLE
Should support tag names with hyphens

### ISSUE THREAD

**Issue by rowanseymour** [Psycojoker/django-hamlpy#6]

**Comment by Psycojoker** [comment]
Can you give an example of a non working situation? It has been working for me since the beginning so I'm a bit surprised.

**Comment by rowanseymour** [comment]
```haml
%ng-div
  More
``` 

becomes 

```html
<ng>-div More</ng>
```

**Comment by Psycojoker** [comment]
Damn, I've misunderstood tags and attributes...

This should be pretty simple to fix https://github.com/Psycojoker/django-hamlpy/pull/8/files#diff-1b5823cc0b651da868cf09a1b041ded8R17
